package bank_classes;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Account {
	private String account_code;
	private String branch_code;
	private History history;
	
	public Account(String account_code, String branch_code, Money initial_balance){
	    this.account_code = account_code;
	    this.branch_code = branch_code;
	    this.history = new History();
	    
	    Date now = new Date();
	    Deposit first = new Deposit(branch_code, initial_balance, account_code, "On creation.");
	    this.add_to_history(first);
	}
	
	public Account(String account_number, Branch branch, Money initial_balance) {
		new Account(account_code,branch.get_code(),initial_balance);
	}
	
	public Money get_balance() {
		return history.sum_transaction_values();	
	}
	
	public History get_history() {
	    return history;
	}
	
	public void add_to_history(Transaction t) {
		history.store_transaction(t);
	}
	
	public String get_account_code(){
		return account_code;
	}
	
	public String get_branch_code() {
		return branch_code;	
	}
	
	// There should be more returning data here? 
	public String toString(){
		return account_code;
	}
}
