package bank_classes;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Account {
	private String account_code;
	private String branch_code;
	private History history;
	
	public Account(String account_code, String branch_code, Money initial_balance){
	    this.account_code = account_code;
	    this.branch_code = branch_code;
	    this.history = new History();
	    
	    Date now = new Date();
	    Deposit t = new Deposit(branch_code, now, initial_balance, account_code, "On creation.");
	    this.add_to_history(t);
	}
	public Money get_balance() {
		return history.sum_transaction_values();	
	}
	
	public History get_history() {
	    return history;
	}
	
	public void add_to_history(Transaction t) {
		history.store_transaction(t);
	}
	
	public String get_branch_code() {
		return branch_code;	
	}
	
	public String toString(){
		return "";
	}
}
