package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : atmUI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class AtmUI extends UI {
	public AtmUI(Bank bank, Branch branch){
		super();
		
	}
	public String deposit(Number ammount, String cashParcelId) {
		return "";
	}

	public String withdraw(Number ammout) {
		return "";
	}

	public String transfer(Number ammount, Client to) {
		return "";
	}

	@Override
	public String operation_result(String effects) {
		// TODO Auto-generated method stub
		return null;
	}
}
