package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : atmUI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class atmUI extends UI {
	public String deposit(Number ammount, String cashParcelId) {
		return null;

	}

	public String withdraw(Number ammout) {
		return null;

	}

	public String transfer(Number ammount, Client to) {
		return null;

	}
}
