package bank_classes;

import bankexceptions.NotFoundException;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : atmUI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class AtmUI extends UI {
	public AtmUI(Bank bank, Branch branch){
		super(bank, branch);
	}
	
	protected void exist_at_system(String username,String branch){
		facade.get_client(username, branch);
	}

	protected String login(String username, String branch, String password) {
		String msg;
		try{
			current_user = 
			if(current_user.passwordMatch(password)) {
				logged_in = true;
				msg = LOGIN_OK;
			} else {
				msg = WRONG_PASSWORD;
			}
		}catch(NotFoundException excep){
			msg = USER_NOT_FOUND;
		}
		return msg;
	}

	public String deposit(Number ammount, String cashParcelId) {
		return ".";
	}

	public String withdraw(Number ammout) {
		return "";
	}

	public String transfer(Number ammount, Client to) {
		return "";
	}

	@Override
	public String operation_result(String effects) {
		// TODO Auto-generated method stub
		return null;
	}
}
