package bank_classes;

import java.util.Collection;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

import bankexceptions.NotFoundException;

public class Bank {
	private int next_account_number;
	public Collection<Branch> branches;
	public Collection<Client> clients;
	
	public Branch get_branch(String branch_code) throws NotFoundException{
		for(Branch each: branches){
			if (each.code_match(branch_code))
				return each;
		}
		throw new NotFoundException(branch_code);
	}

	public Client get_client(String client_username, String branch_id) throws NotFoundException {
		Branch branch;
		branch = this.get_branch(branch_id);
		return branch.get_client(client_username);
	}

	public Clerk get_clerk(String clerk_username, String branch_id) throws NotFoundException {
		Branch branch;
		branch = this.get_branch(branch_id);
		return branch.get_clerk(clerk_username);
	}

	public String new_account_number() {
		String new_number = new Integer(next_account_number).toString();
		update_next_account_number();
		return new_number;
	}
	
	private void update_next_account_number(){
		next_account_number += 1;
	}
	
	public void add_branch(Branch branch) {
		branches.add(branch);
	}

	public void add_clerk_account(Branch branch, Clerk new_user) {
		branch.get_branch_code();
	}

	public void add_client_account(Branch branch, Client new_client, String initial_balance) {
		Money first_deposit;
		String account_number = new_account_number();
		new_client.setUsername(account_number);
		first_deposit = new Money(initial_balance);
		new Account(account_number,branch.get_code(),first_deposit);
		new_client.setAccount();
		branch.add_client(new_client);
	}
	
	public String deposit (String ammount, String cashParcelId, Client holder){
		return "";
	}
	
	public String transfer(Money ammount, String from, String to) {
		return "";
	}
}
