package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BranchUI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class BranchUI extends UI {
	public String add_new_account_to_system(Client client, int initial_balance) {
		return null;

	}

	public String enable_management_functions() {
		return null;

	}

	public String login(String username, String password) {
		return null;

	}
}
