package bank_classes;

import java.util.Calendar;

import bankexceptions.DuplicateException;
import bankexceptions.InvalidTransaction;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BranchUI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//
import bankexceptions.NotFoundException;

public class BranchUI extends UI {
	public BranchUI(Bank bank, Branch branch) {
		// TODO Auto-generated constructor stub
		super(bank,branch);
	}

	protected User exist_at_system(String username,String branch) throws NotFoundException{
		return access_branch.get_clerk(username);
	}


	public String login(String username, String password) {
		String msg;
		try{
			current_user = this.facade.get_clerk(username, access_branch.get_code());
			if(current_user.passwordMatch(password)){
				set_log_in();
				msg = "Login realizado.";
			} else{
				msg = "Senha incorreta!";
			}
		}catch(NotFoundException excep){
			msg = "Funcionário não encontrado.";
		}
		return msg;
	}

	public String add_new_account_to_system() {
		Client client = create_new_client();
		String initial_balance;
		initial_balance = get_string("Quantia inicial: ");
		try{
			this.facade.add_client_account(access_branch, client, initial_balance);
		} catch(InvalidTransaction e)	{
			return INVALID_TRANSACTION;
		} catch(DuplicateException e)	{
			return "Conta duplicada!";
		}
		return "Successo.";
	}

	protected Client create_new_client() {
		String name, surname, cpf;
		display("Informe dos dados do novo cliente: ");
		name = get_string("Nome: ");
		surname = get_string("Sobrenome: ");
		cpf = get_string("CPF: ");
		Calendar bday = enter_birthday();
		return new Client(name, surname, bday, cpf);
	}
	private Calendar enter_birthday() {
		int day, month, year;
		Calendar bday = Calendar.getInstance();
		display("Informe a data de nascimento: ");
		day = Integer.parseInt(get_string("Dia: "));
		month = Integer.parseInt(get_string("Mes: "));
		year = Integer.parseInt(get_string("Ano: "));
		bday.set(year, month, day);
		return bday;
	}
	@Override
	protected MenuOptions[] get_logged_menu_options() {
		// TODO Auto-generated method stub
		return null;
	}
}