package bank_classes;

import java.util.Calendar;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Clerk.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Clerk extends User {

	public Clerk(String name, String surname, Calendar birthday,
			String username, String password) {
		super(name, surname, birthday, username, password);
	}
}
