package bank_classes;

import java.sql.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Deposit.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Deposit extends Transaction {
	public Deposit(String location_access_branch_code, Date date, Money value,
			String this_acc_code) {
		super(location_access_branch_code, date, value, this_acc_code);
		// TODO Auto-generated constructor stub
	}

	public String cashParcelCode;
}
