package bank_classes;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : History.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class History {
	public Money sum_transaction_values() {
		return null;
	
	}
	
	public void store_transaction(Transaction t) {
	
	}
	
	public Transfer[] get_all_transfers() {
		return null;
	
	}
	
	public Withdrawal[] get_all_withdrawals() {
		return null;
	
	}
	
	public Deposit[] get_all_deposits() {
		return null;
	
	}
	
	public History get_transactions(Date from, Date to) {
		return null;
	
	}
}
