package bank_classes;

import java.sql.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transfer.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Transfer extends Transaction {
	public Transfer(String location_access_branch_code, Date date, Money value,
			String this_acc_code) {
		super(location_access_branch_code, date, value, this_acc_code);
		// TODO Auto-generated constructor stub
	}

	public String to_accound_code;
	public String to_branch_code;
	public String from_account_code;
	public String from_branch_code;

	public Account get_from() {
		return null;
	}

	public Account get_to() {
		return null;
	}

	public Money get_value() {
		return super.get_value();
	}

	public void Transfer(Account from, Account to, int Value) {

	}
}
