package bank_classes;

import java.util.Calendar;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transfer.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//


import bankexceptions.InvalidTransaction;

public class Transfer extends Transaction {
	private String to_account_code;
	private String to_branch_code;
	private String from_account_code;
	private String from_branch_code;
	private static Integer last_transfer_id = 0;
	private TransferRole role;
	
	private Transfer( 
			 TransferRole r,
			 String gate_branch_code, 
			 Money value, 
			 String to_acc_code, String to_branch_code, 
			 String from_acc_code,String from_branch_code) {
		super(last_transfer_id.toString(), gate_branch_code,  value);
		this.role = r;
		this.to_account_code = to_acc_code;
		this.to_branch_code = to_branch_code;
		this.from_account_code = from_acc_code;
		this.from_branch_code = from_branch_code;		

	}	

	private static Transfer newInstance(TransferRole role, Branch gate, Money value, Calendar date, Account to, Account from) {
		Transfer transfer	= new Transfer( role, gate.get_code(), value,
								 to.get_account_code(), to.get_branch_code(), 
								 from.get_account_code(), from.get_branch_code());
		transfer.set_date(date);
		return transfer;
	}
	
	public static String add_transfer(Branch origin, Money ammount, Account from, Account to) throws InvalidTransaction{
		Calendar date = Calendar.getInstance();
		Transfer f = newInstance(TransferRole.SEND, origin, ammount,date, from, to);
		Transfer t = newInstance(TransferRole.RECEIVE, origin, ammount,date, from, to);
		from.add_to_history(f);
		to.add_to_history(t);
		last_transfer_id++;		
		return t.toString();
	}
	
	public String get_from() {
		return from_account_code;
	}

	public String get_to() {
		return to_account_code;
	}

	public Money get_value() {
		Money value = super.get_value();
		if(sent_transfer()){
			value = value.minus();
		}
		return value;
	}
	
	private boolean sent_transfer() {
		return (role == TransferRole.SEND);
	}

	public String toString(){
		return "Transfer " + super.get_code() + super.toString() + "\n" +
				" from account:" + from_account_code + " branch: "+ from_branch_code + "\n" +
				" to account:"+ to_account_code + " branch: " + to_branch_code;
	}
}
