package bank_classes;

import java.util.Date;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transaction.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Transaction {
	private String gate_branch_code;
	private Date time_stamp;
	private Money value;
	protected String this_acc_code;

	public Transaction(String this_acc_code, String location_access_branch_code, Date date, Money value){
		this.gate_branch_code = location_access_branch_code;
		this.time_stamp = new Date();
		this.value = value;
		this.this_acc_code = this_acc_code;
	}

	public Transaction(String this_acc_code, String location_access_branch_code, Money value){
		this.gate_branch_code = location_access_branch_code;
		this.time_stamp = new Date();
		this.value = value;
		this.this_acc_code = this_acc_code;
	}

	
	public Money get_value() {
          return value;
	}

	public Date get_date() {
          return time_stamp;
	}

	public boolean newer_than(Date time) {
           return time_stamp.before(time);
	}

	public boolean older_than(Date time) {
           return time_stamp.after(time);
	}

	public boolean in_time_period(Date from, Date to) {
           return older_than(from) && newer_than(to);     
	}
	
	public String toString(){
		return "$" + value.toString() + "at "+ gate_branch_code + " " + time_stamp.toString();
	}
}
