package bank_classes;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transfer.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Transfer extends Transaction {
	private String to_account_code;
	private String to_branch_code;
	private String from_account_code;
	private String from_branch_code;
	private TransferRole role;
	
	public Transfer( 
			 TransferRole r,
			 String gate_branch_code, 
			 Date date, 
			 Money value,
			 String to_acc_code, String to_branch_code, 
			 String from_acc_code,String from_branch_code) {
		super("", gate_branch_code, date, value);
		this.role = r;
		this.to_account_code = to_acc_code;
		this.to_branch_code = to_branch_code;
		this.from_account_code = from_acc_code;
		this.from_branch_code = from_branch_code;		
	}	

	public static Transfer newTransfer(TransferRole r, Branch gate, Money value, Date date, Account to, Account from) {
			return new Transfer( r, gate.get_code(), date, value,
								 to.get_account_code(), to.get_branch_code(), 
								 from.get_account_code(), from.get_branch_code());
	}
	
	public static String execute_transfer(Branch gate, Money ammount, Account from, Account to) {
		Date date = new Date();
		
		Transfer f = newTransfer(TransferRole.SEND, gate, ammount,date, from, to);
		Transfer t = newTransfer(TransferRole.RECEIVE, gate, ammount,date, from, to);
		
		from.add_to_history(f);
		to.add_to_history(t);
		return "Success on transfer.\n";
	}
	
	public String get_from() {
		return from_account_code;
	}

	public String get_to() {
		return to_account_code;
	}

	public Money get_value() {
		Money value = super.get_value();
		if(sent_transfer()){
			value = value.minus();
		}
		return value;
	}
	
	private boolean sent_transfer() {
		if(role == TransferRole.SEND){
			return true;
		}
		return false;
	}

	public String toString(){
		return "Transfer $" + super.toString() + "\n" +
				" from acc:" + from_account_code + " branch: "+ from_branch_code + "\n" +
				" to acc:"+ to_account_code + " branch: " + to_branch_code;
	}
}
