package bank_classes;

import java.util.Calendar;
import java.util.Date;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transaction.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Transaction {
	private String gate_branch_code;
	private Calendar time_stamp;
	private Money value;
	protected String this_acc_code;

	public Transaction(String this_acc_code, String location_access_branch_code, Calendar date, Money value){
		this.gate_branch_code = location_access_branch_code;
		this.time_stamp = date;
		this.value = value;
		this.this_acc_code = this_acc_code;
	}

	public Transaction(String this_acc_code, String location_access_branch_code, Money value){
		this.gate_branch_code = location_access_branch_code;
		this.time_stamp = Calendar.getInstance();
		this.value = value;
		this.this_acc_code = this_acc_code;
	}

	
	public Money get_value() {
          return value;
	}

	public Calendar get_date() {
          return time_stamp;
	}

	public boolean newer_than(Calendar to) {
           return time_stamp.before(to);
	}

	public boolean older_than(Calendar from) {
           return time_stamp.after(from);
	}

	public boolean in_time_period(Calendar from, Calendar to) {
           return older_than(from) && newer_than(to);     
	}
	
	public String toString(){
		return " $" + value.toString() + " at "+ gate_branch_code + " " + time_stamp.toString();
	}
}
