package bank_classes;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class UI {
	private boolean logged_in;
	public User current_user;
	public Branch access_branch;
	public String login(String username, String branch, String password) {
		return "";
	}
	
	public String logout() {
		return null;
	
	}
	
	private void disable_operations() {
	
	}
	
	public boolean isLoggedIn() {
		return logged_in;
	
	}
	
	private String enable_financial_functions() {
		return null;
	
	}
	
	public String deposit(Number ammount, String cashParcelId, Client holder) {
		return "Not implemented!";
	
	}
	
	public String withdraw(Number ammount, Client holder) {
		return "";
	
	}
	
	public String transfer(Number ammount, Client from, Client to) {
		return "";
	}
	
	private void get_period_from_user() {
	    //TODO this is not void
	}
	
	public void get_month_from_user() {
		//TODO this is not void
	}
	
	private String transaction_history(Client holder, Date from, Date to) {
		return "";
	}
	
	private String transaction_history(Client holder, MonthOptionEnum month) {
		return "";
	}
	
	public String transaction_history_to_print(Client holder, TimeOptionEnum statement_type) {
		return "";
	}
	
	public String balance(Client holder) {
		return "";
	}
}
