package bank_classes;

import java.io.InputStreamReader;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//
import java.util.Scanner;

import bankexceptions.NotFoundException;

public abstract class UI {
	protected static final String OPERACAO_FINALIZADA = "Operacao Finalizada";
	protected static final String INVALID_TRANSACTION = "Transacao invalida.";
	private static final String SELECT_ONE_FROM_BELLOW_LIST = "Escolha uma operacao abaixo";
	protected static final String USER_NOT_FOUND = "Usuario nao encontrado!";
	protected static final String WRONG_PASSWORD = "Senha incorreta!";
	protected static final String LOGIN_OK = "Login realizado.";
	private static final String Y_OR_N_PREFFIX_WORD_REGEX = "[YyNn].*";
	private static final String CONFIRM_PREFFIX = "Do you really want to ";
	protected static final String PROMPT = "\n=> ";
	private static final String CLEAR_SCREEN = "\000C";
	protected boolean logged_in;
	protected User current_user;
	protected Branch access_branch;
	protected Bank facade;

	public UI(Bank bank, Branch branch) {
		// Bank and branch data addition
		this.access_branch = branch;
		this.facade = bank;
	}
	// raw input output
	// this method should be overriden for GUI implementations
	public void display(String message){
		System.out.println(message);		
	}
	public  String get_string(String question){
		InputStreamReader cin = new InputStreamReader(System.in);
		Scanner in = new Scanner(cin);
		display(question);
		display(PROMPT);
		String input = in.nextLine();
		in.close();
		return input;
	}

	private static boolean yes_or_no(String yes_or_no){
		return (yes_or_no.toLowerCase().startsWith("y"));
	}

	public boolean confirm(String question){
		boolean valid_answer,answer;
		String input = "y";		
		do{
			input = get_string(CONFIRM_PREFFIX + question);
			valid_answer = input.matches(Y_OR_N_PREFFIX_WORD_REGEX);
		}while(!valid_answer);
		answer = yes_or_no(input);
		return answer;
	}

	protected String logout() {
		logged_in = confirm("logout");
		disable_operations();
		return OPERACAO_FINALIZADA;
	}

	protected abstract User exist_at_system(String username,String branch);
	
	protected String login(String username, String branch, String password) {
		String msg;
		try{
			current_user = exist_at_system(username, branch);
			if(current_user.passwordMatch(password)) {
				logged_in = true;
				msg = LOGIN_OK;
			} else {
				msg = WRONG_PASSWORD;
			}
		}catch(NotFoundException excep){
			msg = USER_NOT_FOUND;
		}
		return msg;
	}


	private void disable_operations() {
		display(CLEAR_SCREEN);
	}
	
	private MenuOptions[] get_unlogged_menu_options(){
		MenuOptions[] restrictions = {
					MenuOptions.LOGIN,
					MenuOptions.EXIT
					};
		return restrictions;
	}
	
	public boolean isLoggedIn() {
		return logged_in;
	}

	private void enable_financial_functions() {
		String answer;
		String menu =  "Escolha uma operacao: \n" +
				"I> Impressaoo saldo \n" +
				"E> Extrato \n" +
				"D> Deposito \n" +
				"W> Saque \n" +
				"T> Transferencia \n" +
				"O> Logout de "+ current_user.getUsername();
		do {
			answer = get_string(menu);
			display(CLEAR_SCREEN);	
		}while(!MenuOptions.validOption(answer, get_unlogged_menu_options()));
		
		display(execute(answer.toCharArray()[0]));
	}

	public void menu(){
		String resposta;
		String username;
		String pass;
		String msg = "Bem vindo ao WAND Bank System. \n" +
				"Escolha uma operacao: \n" +
				"1> Login \n" +
				"2> Sair";
		String loginUser = "Digite o nome de usuario: \n";
		String passwUser = "Digite sua senha: \n";

		do {

			display(msg);
			resposta = get_string(PROMPT);
			display(CLEAR_SCREEN);

		}while(!resposta.equals("1") && !resposta.equals("2"));

		if(resposta.equals("1"))
		{
			display(loginUser);
			username = get_string(PROMPT);
			display(passwUser);
			pass = get_string(PROMPT);
			display(CLEAR_SCREEN);
			login(username, this.access_branch.get_code(), pass);
			if (isLoggedIn())
			{
				logged_menu_loop();
			}
		}
	}

	public String deposit() {
		String ammount;
		String cashParcelId;
		String user;
		Client client;
		display("Digite o nome do usuario a receber o deposito: \n");
		user = get_string(PROMPT);
		try{
			client = this.facade.get_client(user, this.access_branch.get_code());
		}
		catch(NotFoundException e){
			return USER_NOT_FOUND;
		}
		display("Digite a quantia a ser depositada: \n");
		ammount = get_string(PROMPT);
		display("Digite o codigo do envelope: \n");
		cashParcelId = get_string(PROMPT);
		try{
			this.facade.deposit(ammount, cashParcelId, access_branch, client.get_account());
		}
		catch(InvalidTransaction e){
			return INVALID_TRANSACTION;
		}
		return OPERACAO_FINALIZADA;
	}

	public String withdraw() {
		String ammount;
		String user;
		Client client;
		display("Digite o nome do usuario a fazer o saque: \n");
		user = get_string(PROMPT);
		try{
			client = this.facade.get_client(user, this.access_branch.get_code());
		}
		catch(NotFoundException e){
			return USER_NOT_FOUND;
		}
		display("Digite a quantia a ser retirada: \n");
		ammount = get_string(PROMPT);
		return this.facade.withdraw(ammount, access_branch, client.get_account());

	}

	public void unlogged_menu_loop(){
		while(isSystemOn()){
			user_interaction();
		}
	}
	
	char get_next_operation(MenuOptions[] restricted_to_options){
		String input;
		char op_value;
		
		do {
			String menu = MenuOptions.menu(SELECT_ONE_FROM_BELLOW_LIST, restricted_to_options);
			input = get_string(menu);
			op_value = input.toUpperCase().charAt(0);
		}while(! MenuOptions.validOption(op_value,restricted_to_options));
		
		return op_value;
	}
	
	public String execute(char optCode){
		String message = "";
		if(MenuOptions.ATM.compare(optCode)){
		} else if(MenuOptions.BALANCE.compare(optCode)){
			return balance();

		} else if(MenuOptions.BRANCH.compare(optCode)){

		} else if(MenuOptions.DEPOSIT.compare(optCode)){
			return deposit();
		} else if(MenuOptions.EXIT.compare(optCode)){

		} else if(MenuOptions.EXIT_ALL.compare(optCode)){
		} else if(MenuOptions.HISTORY.compare(optCode)){
			return transaction_history();

		} else if(MenuOptions.LOGIN.compare(optCode)){
			//acho que isso nao deveria estar aqui
		} else if(MenuOptions.LOGOUT.compare(optCode)){
			message = logout();
		} else if(MenuOptions.NEW_ACCOUNT.compare(optCode)){
			return add_new_account_to_system();
		} else if(MenuOptions.TRANSFER.compare(optCode)){
			return transfer();
		} else if(MenuOptions.WITHDRAW.compare(optCode)){
			return withdraw();
		} else {
			message = "Opcao invalida.";
		}
		return message;
	}
	
	public void logged_menu_loop(){
		while(isLoggedIn()){
			user_interaction(get_logged_menu_options());
		}
	}
	
	protected abstract MenuOptions[] get_logged_menu_options();

	private void user_interaction(MenuOptions[] restrict_to_options){
		char operation_id = get_next_operation(restrict_to_options);
		String execution_result = execute(operation_id);
		display(execution_result);
	}
	
	public String transfer() {
		String ammount;
		String user;
		Client client;
		String to_account_id;
		String to_branch_id;
		
		display("Digite o nome do usuario: \n");
		user = get_string(PROMPT);
		try{
			client = this.facade.get_client(user, this.access_branch.get_code());
		}
		catch(NotFoundException e){
			return USER_NOT_FOUND;
		}
		
		display("Digite o codigo da conta destino: \n");
		to_account_id = get_string(PROMPT);
		
		display("Digite o codigo da agencia destino: \n");
		to_branch_id = get_string(PROMPT);
		
		display("Digite a quantia a ser transferida: \n");
		ammount = get_string(PROMPT);
		try{
			this.facade.transfer(ammount, to_account_id, to_branch_id, access_branch, client.get_account());
		}
		catch(NoutFoundException e){
			return USER_NOT_FOUND;
		}
		catch(InvalidTransaction e){
			return INVALID_TRANSACTION;
		}
		return OPERACAO_FINALIZADA;
	}
	
	private Date get_date_from_user(){
		Date date = null;
		String date_s;
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		while (date == null){
			date_s = get_string("");
			try{
				date = sdf.parse(date_s);
				return date;
			}catch(ParseException e)
			{
				display("Entrada Invalida!");
				display(CLEAR_SCREEN);
				date = null;
			}
		}
	}
	
	protected void set_log_in()
	{
		logged_in = true;
	}

	public Calendar[] get_period_from_user() {
		Date date;
		Calendar[] period = new Calendar[2];
		
		display("Informe o período a ser visualizado:");
		display("Data de início (aaaa-mm-dd): \n");
		date = get_date_from_user();
		period[0].setTime(date);
		display("Data final (aaa-mm-dd): \n");
		date = get_date_from_user();		
		period[1].setTime(date);
		return period;
		
	}

	public Calendar[] get_month_from_user() {
		Calendar calend;
		Calendar[] period = new Calendar[2];
		String month;
		Date dateNow = new Date();
		
		display("Informe o mês a ser visualizado: (1-12; ex: Janeiro = 1) \n");
		month = get_string("");
		calend = Calendar.getInstance();
		calend.set(dateNow.getYear(), Integer.parseInt(month), 1);
		period[0] = calend;
		calend.add(Calendar.MONTH, 1);
		period[1] = calend;
		return period;
	}

	private String transaction_history() {
		String user;
		Client client;
		History history;
		String opt;
		Calendar[] period = new Calendar[2];
		display("Digite o nome do usuario: \n");
		user = get_string(PROMPT);
		try{
			client = this.facade.get_client(user, this.access_branch.get_code());
		}
		catch(NotFoundException e){
			return USER_NOT_FOUND;
		}
		history = client.get_account().get_history();
		display(SELECT_ONE_FROM_BELLOW_LIST);
		
		do{
		display("1> Visualizar historico do mes anterior \n" +
				"2> Selecionar periodo a ser visualizado");
		opt = get_string("");
		}while(!opt.equals("1") && !opt.equals("2"));
		
		if(opt.equals("1"))
		{

			period = get_month_from_user();
		}
		if(opt.equals("2"))
		{
			
			period = get_period_from_user();
		}
		
		try{
			return history.get_transactions(period[0], period[1]).toString();
		}
		catch(InvalidTransaction e)
		{
			return INVALID_TRANSACTION;
		}
	
	}

	public String transaction_history_to_print() {
		return "";
	}

	public String balance() {
		String user;
		Client client;
		display("Digite o nome do usuario: \n");
		user = get_string(PROMPT);
		try{
			client = this.facade.get_client(user, this.access_branch.get_code());
		}
		catch(NotFoundException e){
			return USER_NOT_FOUND;
		}
		Date dateNow = new Date();
		return "Seu saldo é " + client.get_account().get_balance().toString() +
				"\n Visto às " + dateNow.toString();
	}
}