package bank_classes;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Withdrawal.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Withdrawal extends Transaction {
	
	public Withdrawal(String this_acc_code, String location_access_code, Date date, Money value){
		super(this_acc_code,location_access_code, date, value);
	}

	public Withdrawal(Account acc, Branch location_access, Date date, Money value){
		super(acc.get_account_code(),location_access.get_code(), date, value);
	}

	public Withdrawal(Account acc, Branch location_access, Money value){
		super(acc.get_account_code(),location_access.get_code(), value);
	}

	
	public Money get_value() {
        return this.get_value().minus();
	}
}
